#FIXME: can we remove that CR?
apiVersion: sro.openshift.io/v1beta1
kind: SpecialResource
metadata:
  name: {{ .Release.Name }}-preamble
spec:
  chart:
    name: preamble
    version: 0.0.1
    repository:
      name: example
      url: file:///charts/example/
      insecure_skip_tls_verify: false
  namespace: preamble
  nodeSelector:
    node-role.kubernetes.io/worker: ""
{{- if eq .Values.platform.type "ocp" }}
---
apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: {{ .Release.Name }}-cluster-operator
spec: {}
status:
  versions:
    - name: operator
      version: "0.0.1-snapshot"
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: manager-controller
  name: {{ .Release.Name }}-manager-controller-service-monitor
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      path: /metrics
      port: https
      scheme: https
      interval: 30s
      tlsConfig:
        caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
        serverName: special-resource-controller-manager-metrics-service.openshift-special-resource-operator.svc
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end }}
