apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-manager-controller
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 499
        runAsGroup: 499
      containers:
        - name: manager
          imagePullPolicy: Always # TODO
          image: {{ .Values.deployment.image.name }}:{{ .Values.deployment.image.tag }}
          command:
            - /manager
          args:
            - "--enable-leader-election"
            {{- if eq .Values.platform.type "ocp" }}
            - "--metrics-addr=127.0.0.1:8080"
            {{- end }}
          env:
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: RELEASE_VERSION
              value: "0.0.1-snapshot"
            - name: SSL_CERT_DIR
              value: "/etc/pki/tls/certs"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          resources:
            limits:
              cpu: 300m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 500Mi
          volumeMounts:
          - name: cache-volume
            mountPath: /cache
          - name: cred-volume
            mountPath: /home/nonroot/.docker
        {{- if eq .Values.platform.type "ocp" }}
        - name: kube-rbac-proxy
          image: registry.redhat.io/openshift4/ose-kube-rbac-proxy
          args:
            - "--secure-listen-address=0.0.0.0:8443"
            - "--upstream=http://127.0.0.1:8080/"
            - "--logtostderr=true"
            - "--v=10"
            - "--tls-cert-file=/etc/secrets/tls.crt"
            - "--tls-private-key-file=/etc/secrets/tls.key"
            - "--tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256"
          ports:
            - containerPort: 8443
              protocol: TCP
              name: https
          volumeMounts:
            - name: {{ .Release.Name }}-tls
              mountPath: /etc/secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            readOnlyRootFilesystem: true
        {{- end }}
      volumes:
        - name: cache-volume
          emptyDir: {}
        - name: cred-volume
          emptyDir: {}
        {{- if eq .Values.platform.type "ocp" }}
        - name: {{ .Release.Name }}-tls
          secret:
            secretName: {{ .Release.Name }}-tls
        {{- end }}
      serviceAccountName: {{ .Release.Name }}-manager-service-account
      terminationGracePeriodSeconds: 10
