apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ .Release.Name }}-tls
  labels:
    control-plane: manager-controller
  name: {{ .Release.Name }}-manager-controller-metrics-service
spec:
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: https
  selector:
    control-plane: manager-controller
