name: k8s-e2e

on:
  pull_request_target:
    types: [opened, synchronize, reopened, labeled]
    paths-ignore:
      - "**/README.md"
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}_build_$${ github.head_ref }}
      cancel-in-progress: true
    if: (github.event.action == 'labeled' && github.event.label.name == 'ok-to-test') ||
        (github.event.pull_request.head.repo.full_name == 'openshift-psap/special-resource-operator')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 10
    - run: make local-image-build
      env:
        TAG: pr-${{ steps.short-sha.outputs.sha }}
    - uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD}}
    - run: make local-image-push
      env:
        TAG: pr-${{ steps.short-sha.outputs.sha }}
  e2e:
    name: e2e-test
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}_e2e-test_$${ github.head_ref }}
      cancel-in-progress: true
    if: (github.event.action == 'labeled' && github.event.label.name == 'ok-to-test') ||
        (github.event.pull_request.head.repo.full_name == 'openshift-psap/special-resource-operator')
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        persist-credentials: false
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.2'
    - uses: benjlevesque/short-sha@v1.2
      id: short-sha
      with:
        length: 10
    - uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"
    - name: Testing
      run: |
        export KUBECONFIG="$(kind get kubeconfig-path)"
        kubectl cluster-info
    - run: kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.8.2/nfd-master.yaml.template
    - run: kubectl rollout status deployment -n node-feature-discovery nfd-master --timeout=300s

    - run: kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/node-feature-discovery/v0.8.2/nfd-worker-daemonset.yaml.template
    - run: kubectl rollout status daemonset -n node-feature-discovery nfd-worker --timeout=300s

    - run: make go-deploy-manifests
      env:
        TAG: pr-${{ steps.short-sha.outputs.sha }}
        PLATFORM: k8s
    - run: kubectl describe deploy/special-resource-controller-manager -n openshift-special-resource-operator
    - run: kubectl logs deploy/special-resource-controller-manager -n openshift-special-resource-operator -c manager
    - run: kubectl describe pod/$(kubectl get pods -n openshift-special-resource-operator | tail -n1 | cut -d" " -f1) -n openshift-special-resource-operator
    - run: kubectl logs pod/$(kubectl get pods -n openshift-special-resource-operator | tail -n1 | cut -d" " -f1) -n openshift-special-resource-operator -c manager
    - run: kubectl rollout status deployment -n openshift-special-resource-operator special-resource-controller-manager --timeout=300s

    - run: kubectl apply -f  charts/example/centos-simple-kmod-0.0.1/centos-simple-kmod.yaml
    - run: sleep 360
    - run: kubectl logs `kubectl get pod -n openshift-special-resource-operator | grep special | awk '{ print $1 }'` -c manager -n openshift-special-resource-operator
